### ISSUE TITLE
Addon is killed by supervisor when camera is offline.

### ISSUE THREAD

**Issue by BugsBunny1403** [Botond24/prusa_connect_rtsp_homeassistant#1]
Hello, this addon is killed by supervisor s6 when camera is offline.
But it's not a good news when 2 cam is on and just 1 is offline for any reason.
Can you have an idea for block this happening or set an thresold of error for minimize impact ?
![image](https://github.com/Botond24/prusa_connect_rtsp_homeassistant/assets/36540728/164e6b96-6b28-42e4-af2e-697af0d7991c)

**Comment by davorch** [comment]
the same thing. Strange
If the camera was off for some time addon stops.
watchdog does not help. 
It needs to run again manually.

**Comment by BugsBunny1403** [comment]
Can author help us ?

**Comment by davorch** [comment]
> Can author help us ?

Since we have HA I temporarily decided with the help of the command in Telegram.
for some reason, the service drop is not automatically detected.

So I just send a command '/up' to telegram and it works again :)

`      - id: TEST            
        alias: TEST /TEST
        initial_state: true
        trigger:
          - platform: event
            event_type: telegram_command
            event_data:
              command: '/up'
        action:
          - service: hassio.addon_restart
            data:
                addon: 3a876dbe_prusa-conncect-rtsp`

**Comment by BugsBunny1403** [comment]
Up

**Comment by BugsBunny1403** [comment]
@Botond24 are you still following the development of this Home assistant addon? It's a simple mistake I guess but I don't know enough about it to correct it.

**Comment by BugsBunny1403** [comment]
Missclick

**Comment by BugsBunny1403** [comment]
Missclick

**Comment by Botond24** [comment]
So sorry for making everyone wait, I didn't get any notifications about the state of the project, I will take a look at the code again soon to try and figure this out

**Comment by BugsBunny1403** [comment]
Nice, i go to test but i think your repo for home assistant aren't here now ?

**Comment by Botond24** [comment]
yes, sorry i moved all my hassio addons into a single repo at https://github.com/Botond24/hassio-addons

**Comment by Botond24** [comment]
but if there is interest i will move it back to its own repository, when i did the move, i didn't realize other people were also using this addon

**Comment by davorch** [comment]
> but if there is interest i will move it back to its own repository, when i did the move, i didn't realize other people were also using this addon

Can you move it back to shere with us? I used it for Home Assistant. I did not find any other such addons for HA

**Comment by Botond24** [comment]
I have moved the whole repository back here, you should be able to continue using it

**Comment by davorch** [comment]
Thanks!

**Comment by davorch** [comment]
@Botond24 I can't add your repo to HA. Without any issues. Just red icon

![Image](https://github.com/user-attachments/assets/7ab37b3e-dc7e-4745-bc58-0f9c3a03b9ac)

**Comment by Botond24** [comment]
It seems to work for me, but I did fix the addon badge, so maybe that was the problem
